### ISSUE TITLE
HTTPError: 404 Client Error: Not Found for url: http://freqtrade-proxy:8080/kucoin/api/v1/currencies

### ISSUE THREAD

**Issue by bibinvargheset** [mikekonan/freqtrade-proxy#2]
version: '3'
services:
  freqtrade-proxy:
    image: mikekonan/freqtrade-proxy:main
    restart: unless-stopped
    container_name: freqtrade-proxy

  Combined_NFIv7_SMA_Rallipanos_20210707:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: always
    container_name: Combined_NFIv7_SMA_Rallipanos_20210707
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "0.0.0.0:8100:8080"
    environment :
      - TZ=Asia/Kolkata

    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Combined_NFIv7_SMA_Rallipanos_20210707.log
      --db-url sqlite:////freqtrade/user_data/db/Combined_NFIv7_SMA_Rallipanos_20210707.tradesv3.sqlite
      --config /freqtrade/user_data/config/config_kucoin_dry.json
      --config /freqtrade/user_data/config/api.json

      --config /freqtrade/user_data/config/kucoin-proxy.json
      --strategy Combined_NFIv7_SMA_Rallipanos_20210707

{
    "exchange": {
        "name": "kucoin",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "enableRateLimit": false,
            "urls": {
                "api": {
                    "public": "http://freqtrade-proxy:8080/kucoin",
                    "private": "http://freqtrade-proxy:8080/kucoin"
                }
            }
        },
        "ccxt_async_config": {
            "enableRateLimit": false
        }
    }
}

2021-11-14 21:02:30,355 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False, 'urls': {'api': {'public': 'http://freqtrade-proxy:8080/kucoin', 'private': 'http://freqtrade-proxy:8080/kucoin'}}}
2021-11-14 21:02:30,365 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': False, 'urls': {'api': {'public': 'http://freqtrade-proxy:8080/kucoin', 'private': 'http://freqtrade-proxy:8080/kucoin'}}, 'rateLimit': 300}
2021-11-14 21:02:30,375 - freqtrade.exchange.exchange - INFO - Using Exchange "KuCoin"
2021-11-14 21:02:30,879 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 613, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://freqtrade-proxy:8080/kucoin/api/v1/currencies

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 339, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1411, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/kucoin.py", line 511, in fetch_currencies
    response = self.publicGetCurrencies(params)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 506, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 629, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/kucoin.py", line 2249, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, self.id + ' ' + message)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 520, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.NotSupported: kucoin Not Found
2021-11-14 21:02:30,884 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2021-11-14 21:02:30,884 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 153, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 370, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.

**Comment by mikekonan** [comment]
Is proxy service declared in the same docker-compose as a bot? 
Can you docker pull mikekonan/freqtrade-proxy:main?

**Comment by bibinvargheset** [comment]
gr8 job buddy you solved one of the biggest issues in freqtrade, i must have had yesterdays version
